import { keccak256, parseEther, stringToHex, type Address, type Hex } from "viem";
import type { CallLogRow } from "@/hooks/useMyCallLogs";

/** Demo user address shown on sample rows (not a real wallet). */
export const DEMO_CALL_HISTORY_USER = "0xCa1100000000000000000000000000000000000001" as Address;

function h(label: string): Hex {
  return keccak256(stringToHex(label)) as Hex;
}

/** Unix seconds — spread over recent hours for a realistic timeline. */
const BASE_TS = BigInt(Math.floor(new Date("2026-04-19T14:20:00Z").getTime() / 1000));

/**
 * Sample call log rows merged with on-chain logs in the user dashboard (demo UI).
 */
export const DEMO_CALL_HISTORY: readonly CallLogRow[] = [
  {
    id: "demo-call-1",
    isDemo: true,
    providerId: 900_001n,
    caller: DEMO_CALL_HISTORY_USER,
    requestHash: h("call:req:demo-1"),
    responseHash: h("call:res:demo-1"),
    paid: parseEther("0.001"),
    callId: 10_401n,
    blockNumber: 18_452_110n,
    txHash: h("tx:demo-1"),
    usageUnits: 428n,
    recordedAt: BASE_TS - 1800n,
    requestFormat: 1,
    responseFormat: 1,
    settlementStatus: 1,
    latencyMs: 205,
    promptSummary: "Explain zero-knowledge in one paragraph",
  },
  {
    id: "demo-call-2",
    isDemo: true,
    providerId: 900_002n,
    caller: DEMO_CALL_HISTORY_USER,
    requestHash: h("call:req:demo-2"),
    responseHash: h("call:res:demo-2"),
    paid: parseEther("0.004"),
    callId: 10_402n,
    blockNumber: 18_451_884n,
    txHash: h("tx:demo-2"),
    usageUnits: 612n,
    recordedAt: BASE_TS - 5400n,
    requestFormat: 1,
    responseFormat: 1,
    settlementStatus: 1,
    latencyMs: 352,
    promptSummary: "Translate the following JSON schema to TypeScript types",
  },
  {
    id: "demo-call-3",
    isDemo: true,
    providerId: 900_001n,
    caller: DEMO_CALL_HISTORY_USER,
    requestHash: h("call:req:demo-3"),
    responseHash: h("call:res:demo-3"),
    paid: parseEther("0.001"),
    callId: 10_403n,
    blockNumber: 18_451_602n,
    txHash: h("tx:demo-3"),
    usageUnits: 891n,
    recordedAt: BASE_TS - 10_200n,
    requestFormat: 1,
    responseFormat: 1,
    settlementStatus: 1,
    latencyMs: 198,
    promptSummary: "Draft a short product changelog for v0.3.0",
  },
  {
    id: "demo-call-4",
    isDemo: true,
    providerId: 900_003n,
    caller: DEMO_CALL_HISTORY_USER,
    requestHash: h("call:req:demo-4"),
    responseHash: h("call:res:demo-4"),
    paid: parseEther("0.0002"),
    callId: 10_404n,
    blockNumber: 18_451_210n,
    txHash: h("tx:demo-4"),
    usageUnits: 1240n,
    recordedAt: BASE_TS - 18_600n,
    requestFormat: 1,
    responseFormat: 1,
    settlementStatus: 1,
    latencyMs: 91,
    promptSummary: "List edge cases for idempotent POST retries",
  },
  {
    id: "demo-call-5",
    isDemo: true,
    providerId: 900_002n,
    caller: DEMO_CALL_HISTORY_USER,
    requestHash: h("call:req:demo-5"),
    responseHash: h("call:res:demo-5"),
    paid: parseEther("0.004"),
    callId: 10_405n,
    blockNumber: 18_450_955n,
    txHash: h("tx:demo-5"),
    usageUnits: 334n,
    recordedAt: BASE_TS - 26_400n,
    requestFormat: 1,
    responseFormat: 1,
    settlementStatus: 1,
    latencyMs: 318,
    promptSummary: "Summarize audit findings from the pasted excerpt",
  },
  {
    id: "demo-call-6",
    isDemo: true,
    providerId: 900_003n,
    caller: DEMO_CALL_HISTORY_USER,
    requestHash: h("call:req:demo-6"),
    responseHash: h("call:res:demo-6"),
    paid: parseEther("0.0002"),
    callId: 10_406n,
    blockNumber: 18_450_420n,
    txHash: h("tx:demo-6"),
    usageUnits: 2102n,
    recordedAt: BASE_TS - 43_200n,
    requestFormat: 1,
    responseFormat: 1,
    settlementStatus: 1,
    latencyMs: 104,
    promptSummary: "Generate unit tests for parseHeaderList()",
  },
];
