/**
 * Minimal ABI for DeOpenRouterMarketplace — keep in sync with
 * contracts/src/DeOpenRouterMarketplace.sol
 */
export const marketplaceAbi = [
  { type: "function", name: "MIN_STAKE", stateMutability: "view", inputs: [], outputs: [{ type: "uint256", name: "" }] },
  { type: "function", name: "priceDelayBlocks", stateMutability: "view", inputs: [], outputs: [{ type: "uint256", name: "" }] },
  { type: "function", name: "SETTLEMENT_SETTLED", stateMutability: "view", inputs: [], outputs: [{ type: "uint8", name: "" }] },
  { type: "function", name: "slashOperator", stateMutability: "view", inputs: [], outputs: [{ type: "address", name: "" }] },
  { type: "function", name: "nextProviderId", stateMutability: "view", inputs: [], outputs: [{ type: "uint256", name: "" }] },
  { type: "function", name: "nextCallId", stateMutability: "view", inputs: [], outputs: [{ type: "uint256", name: "" }] },
  { type: "function", name: "nextAuditId", stateMutability: "view", inputs: [], outputs: [{ type: "uint256", name: "" }] },
  { type: "function", name: "nextSlashId", stateMutability: "view", inputs: [], outputs: [{ type: "uint256", name: "" }] },
  { type: "function", name: "nextSlashProposalId", stateMutability: "view", inputs: [], outputs: [{ type: "uint256", name: "" }] },
  { type: "function", name: "slashTreasury", stateMutability: "view", inputs: [], outputs: [{ type: "address", name: "" }] },
  { type: "function", name: "slashChallengePeriodBlocks", stateMutability: "view", inputs: [], outputs: [{ type: "uint256", name: "" }] },
  { type: "function", name: "pendingSlashOperator", stateMutability: "view", inputs: [], outputs: [{ type: "address", name: "" }] },
  { type: "function", name: "pendingAuditRecorder", stateMutability: "view", inputs: [], outputs: [{ type: "address", name: "" }] },
  { type: "function", name: "auditRecorder", stateMutability: "view", inputs: [], outputs: [{ type: "address", name: "" }] },
  { type: "function", name: "latestAuditRound", stateMutability: "view", inputs: [{ type: "uint256", name: "providerId" }], outputs: [{ type: "uint256", name: "" }] },
  { type: "function", name: "activeAuditRound", stateMutability: "view", inputs: [{ type: "uint256", name: "providerId" }], outputs: [{ type: "uint256", name: "" }] },
  { type: "function", name: "isAuditor", stateMutability: "view", inputs: [{ type: "address", name: "" }], outputs: [{ type: "bool", name: "" }] },
  {
    type: "function",
    name: "providers",
    stateMutability: "view",
    inputs: [{ type: "uint256", name: "" }],
    outputs: [
      { type: "address", name: "owner" },
      { type: "string", name: "modelId" },
      { type: "string", name: "modelVersion" },
      { type: "bytes32", name: "endpointCommitment" },
      { type: "bytes32", name: "capabilityHash" },
      { type: "uint256", name: "pricePerCall" },
      { type: "uint256", name: "pendingPriceWei" },
      { type: "uint256", name: "pendingEffectiveBlock" },
      { type: "uint256", name: "stake" },
      { type: "uint256", name: "stakeLockBlocks" },
      { type: "bool", name: "active" },
      { type: "string", name: "metadataURI" },
      { type: "bytes32", name: "metadataHash" },
      { type: "bytes32", name: "identityHash" },
      { type: "uint256", name: "createdAtBlock" },
      { type: "uint256", name: "updatedAtBlock" },
      { type: "uint256", name: "slashedTotal" },
      { type: "uint256", name: "lastSlashedAtBlock" },
    ],
  },
  {
    type: "function",
    name: "getProviderCore",
    stateMutability: "view",
    inputs: [{ type: "uint256", name: "providerId" }],
    outputs: [
      { type: "address", name: "owner" },
      { type: "bytes32", name: "endpointCommitment" },
      { type: "uint256", name: "pricePerCall" },
      { type: "uint256", name: "stake" },
      { type: "bool", name: "active" },
      { type: "uint256", name: "createdAtBlock" },
      { type: "uint256", name: "updatedAtBlock" },
      { type: "uint256", name: "slashedTotal" },
      { type: "uint256", name: "lastSlashedAtBlock" },
    ],
  },
  {
    type: "function",
    name: "getEffectivePrice",
    stateMutability: "view",
    inputs: [{ type: "uint256", name: "providerId" }],
    outputs: [
      { type: "uint256", name: "priceWei" },
      { type: "bool", name: "hasPending" },
      { type: "uint256", name: "pendingPrice" },
      { type: "uint256", name: "pendingAppliesAtBlock" },
    ],
  },
  {
    type: "function",
    name: "register",
    stateMutability: "payable",
    inputs: [
      {
        name: "info",
        type: "tuple",
        components: [
          { name: "modelId", type: "string" },
          { name: "modelVersion", type: "string" },
          { name: "endpointCommitment", type: "bytes32" },
          { name: "capabilityHash", type: "bytes32" },
          { name: "pricePerCall", type: "uint256" },
          { name: "stakeLockBlocks", type: "uint256" },
          { name: "metadataURI", type: "string" },
          { name: "metadataHash", type: "bytes32" },
          { name: "identityHash", type: "bytes32" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "updateProviderMetadata",
    stateMutability: "nonpayable",
    inputs: [
      { name: "providerId", type: "uint256" },
      {
        name: "update",
        type: "tuple",
        components: [
          { name: "metadataURI", type: "string" },
          { name: "metadataHash", type: "bytes32" },
          { name: "identityHash", type: "bytes32" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "announcePriceChange",
    stateMutability: "nonpayable",
    inputs: [
      { type: "uint256", name: "providerId" },
      { type: "uint256", name: "newPrice" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "deactivate",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256", name: "providerId" }],
    outputs: [],
  },
  {
    type: "function",
    name: "invoke",
    stateMutability: "payable",
    inputs: [
      { type: "uint256", name: "providerId" },
      { type: "bytes32", name: "requestHash" },
      { type: "bytes32", name: "responseHash" },
      { type: "uint8", name: "requestFormat" },
      { type: "uint8", name: "responseFormat" },
      { type: "uint256", name: "usageUnits" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "withdrawStake",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256", name: "providerId" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setSlashTreasury",
    stateMutability: "nonpayable",
    inputs: [{ type: "address", name: "newTreasury" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setSlashChallengePeriodBlocks",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256", name: "blocks_" }],
    outputs: [],
  },
  {
    type: "function",
    name: "proposeSlashOperator",
    stateMutability: "nonpayable",
    inputs: [{ type: "address", name: "newOperator" }],
    outputs: [],
  },
  {
    type: "function",
    name: "acceptSlashOperator",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "cancelSlashOperatorProposal",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "proposeAuditRecorder",
    stateMutability: "nonpayable",
    inputs: [{ type: "address", name: "newRecorder" }],
    outputs: [],
  },
  {
    type: "function",
    name: "acceptAuditRecorder",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "cancelAuditRecorderProposal",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "setAuditor",
    stateMutability: "nonpayable",
    inputs: [
      { type: "address", name: "auditor" },
      { type: "bool", name: "allowed" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "beginAuditRound",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256", name: "providerId" }],
    outputs: [{ type: "uint256", name: "roundId" }],
  },
  {
    type: "function",
    name: "attestAudit",
    stateMutability: "nonpayable",
    inputs: [
      { type: "uint256", name: "providerId" },
      { type: "uint256", name: "roundId" },
      { type: "bytes32", name: "reportHash" },
      { type: "uint8", name: "riskLevel" },
      { type: "string", name: "reportUri" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "proposeSlash",
    stateMutability: "nonpayable",
    inputs: [
      { type: "uint256", name: "providerId" },
      { type: "uint256", name: "amount" },
      { type: "bytes32", name: "reasonHash" },
      { type: "uint256", name: "relatedAuditRound" },
      { type: "bytes32", name: "reportHash" },
    ],
    outputs: [{ type: "uint256", name: "proposalId" }],
  },
  {
    type: "function",
    name: "challengeSlashProposal",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256", name: "proposalId" }],
    outputs: [],
  },
  {
    type: "function",
    name: "finalizeSlashProposal",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256", name: "proposalId" }],
    outputs: [],
  },
  {
    type: "function",
    name: "recordAudit",
    stateMutability: "nonpayable",
    inputs: [
      { type: "uint256", name: "providerId" },
      { type: "bytes32", name: "reportHash" },
      { type: "uint8", name: "riskLevel" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "recordAuditWithUri",
    stateMutability: "nonpayable",
    inputs: [
      { type: "uint256", name: "providerId" },
      { type: "bytes32", name: "reportHash" },
      { type: "uint8", name: "riskLevel" },
      { type: "string", name: "reportUri" },
    ],
    outputs: [],
  },
] as const;

/** Hash preimage format for the web MVP (must match hashing in page.tsx). */
export const REQUEST_FORMAT_V1 = 1;
export const RESPONSE_FORMAT_V1 = 1;
